"""add text_content to assets

Revision ID: fa1f7a3269d6
Revises: d155e42785b1
Create Date: 2026-05-03 17:22:14.458861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1f7a3269d6'
down_revision: Union[str, Sequence[str], None] = 'd155e42785b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('text_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'text_content')
    # ### end Alembic commands ###
